version: "3"

tasks:
  install-protoc:
    aliases:
      - protoc
    desc: "Install protoc compiler using apt"
    cmds:
      - sudo apt update
      - sudo apt install -y protobuf-compiler
      - protoc --version

  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/thumbnail/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative